### ISSUE TITLE
Default value in TwiLiquidCrystal::setCursor causes compilation error in Arduino IDE

### ISSUE THREAD

**Issue by Windowsfreak** [arnakazim/TwiLiquidCrystal-library#2]
Apparently, the Arduino compiler complains when default values are set or overwritten in .cpp files, as the definitions already exist in the .h file.

```
TwiLiquidCrystalTwi.cpp:114:62: error: default argument given for parameter 2 of 'void TwiLiquidCrystal::setCursor(uint8_t, uint8_t)'
TwiLiquidCrystal.h:118:10: error: after previous specification in 'void TwiLiquidCrystal::setCursor(uint8_t, uint8_t)'
```

In `TwiLiquidCrystalTwi.cpp`, just replace:
```C
void TwiLiquidCrystal::setCursor(uint8_t col, uint8_t row = 0) {
  ...
}
```
with
```C
void TwiLiquidCrystal::setCursor(uint8_t col, uint8_t row) {
  ...
}
```
to make it compile.

**Comment by arnakazim** [comment]
Thanks for the issue report.

You are right about the default value. I will correct the code, but can you tell me what compiler and target board are you using? I cannot reproduce this error.
