### ISSUE TITLE
Spelling error in Arduino Library Title

### ISSUE THREAD

**Issue by kestrel79** [arnakazim/TwiLiquidCrystal-library#3]
When searching in the Arduino Library Manager, there is a spelling error in the title:

TwiLiquidCrytal (vs. TwiLiquidCrystal)

Also causes problems when including the library as it includes this error.  

Excellent library otherwise. Thanks.

**Comment by arnakazim** [comment]
Thanks a lot for your feedback! 😀
I've corrected the spelling error. The update should be available soon in the Arduino Library Manager.
